export const AUTH_REQUESTING = 'AUTH_REQUESTING';
export const SET_TOKEN = 'SET_TOKEN';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS'
export const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS'